function Jacobian_bQo_dot_to_bQo = Jacobian_bQo_dot_to_bQo(oomegao)
%Jacobian_bQo_dot_to_bQo
%    Jacobian_bQo_dot_to_bQo = Jacobian_bQo_dot_to_bQo(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Mar-2025 15:31:44

oomegao1 = oomegao(1,:);
oomegao2 = oomegao(2,:);
oomegao3 = oomegao(3,:);
t2 = oomegao1./2.0;
t3 = oomegao2./2.0;
t4 = oomegao3./2.0;
t5 = -t2;
t6 = -t3;
t7 = -t4;
Jacobian_bQo_dot_to_bQo = reshape([0.0,t2,t3,t4,t5,0.0,t7,t3,t6,t4,0.0,t5,t7,t6,t2,0.0],[4,4]);
end
