function Jacobian_quaternion_product_left = Jacobian_quaternion_product_left(Qright)
%Jacobian_quaternion_product_left
%    Jacobian_quaternion_product_left = Jacobian_quaternion_product_left(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Mar-2025 16:59:57

Q21 = Qright(1,:);
Q22 = Qright(2,:);
Q23 = Qright(3,:);
Q24 = Qright(4,:);
t2 = -Q22;
t3 = -Q23;
t4 = -Q24;
Jacobian_quaternion_product_left = reshape([Q21,Q22,Q23,Q24,t2,Q21,t4,Q23,t3,Q24,Q21,t2,t4,t3,Q22,Q21],[4,4]);
end
