function Jacobian_bQo_dot_to_oomegao = Jacobian_bQo_dot_to_oomegao(bQo)
%Jacobian_bQo_dot_to_oomegao
%    Jacobian_bQo_dot_to_oomegao = Jacobian_bQo_dot_to_oomegao(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Mar-2025 15:35:09

bQo1 = bQo(1,:);
bQo2 = bQo(2,:);
bQo3 = bQo(3,:);
bQo4 = bQo(4,:);
t2 = bQo1./2.0;
t3 = bQo2./2.0;
t4 = bQo3./2.0;
t5 = bQo4./2.0;
t6 = -t3;
t7 = -t4;
t8 = -t5;
Jacobian_bQo_dot_to_oomegao = reshape([t6,t2,t5,t7,t7,t8,t2,t3,t8,t4,t6,t2],[4,3]);
end
