function Jacobian_bpo_dot_to_bQo = Jacobian_bpo_dot_to_bQo(bQo,ovo)
%Jacobian_bpo_dot_to_bQo
%    Jacobian_bpo_dot_to_bQo = Jacobian_bpo_dot_to_bQo(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Mar-2025 15:14:01

bQo1 = bQo(1,:);
bQo2 = bQo(2,:);
bQo3 = bQo(3,:);
bQo4 = bQo(4,:);
ovo1 = ovo(1,:);
ovo2 = ovo(2,:);
ovo3 = ovo(3,:);
t2 = bQo1.*ovo1.*2.0;
t3 = bQo1.*ovo2.*2.0;
t4 = bQo2.*ovo1.*2.0;
t5 = bQo1.*ovo3.*2.0;
t6 = bQo2.*ovo2.*2.0;
t7 = bQo3.*ovo1.*2.0;
t8 = bQo2.*ovo3.*2.0;
t9 = bQo3.*ovo2.*2.0;
t10 = bQo4.*ovo1.*2.0;
t11 = bQo3.*ovo3.*2.0;
t12 = bQo4.*ovo2.*2.0;
t13 = bQo4.*ovo3.*2.0;
Jacobian_bpo_dot_to_bQo = reshape([t11-t12,-t8+t10,t6-t7,t9+t13,-t5+t7-bQo2.*ovo2.*4.0,t3+t10-bQo2.*ovo3.*4.0,t5+t6-bQo3.*ovo1.*4.0,t4+t13,-t2+t12-bQo3.*ovo3.*4.0,-t3+t8-bQo4.*ovo1.*4.0,t2+t11-bQo4.*ovo2.*4.0,t4+t9],[3,4]);
end
