function Jacobian_quaternion_product_right = Jacobian_quaternion_product_right(Qleft)
%Jacobian_quaternion_product_right
%    Jacobian_quaternion_product_right = Jacobian_quaternion_product_right(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Mar-2025 17:00:19

Q11 = Qleft(1,:);
Q12 = Qleft(2,:);
Q13 = Qleft(3,:);
Q14 = Qleft(4,:);
t2 = -Q12;
t3 = -Q13;
t4 = -Q14;
Jacobian_quaternion_product_right = reshape([Q11,Q12,Q13,Q14,t2,Q11,Q14,t3,t3,t4,Q11,Q12,t4,Q13,t2,Q11],[4,4]);
end
