function Jacobian_otwisto_dot_to_bQo = Jacobian_otwisto_dot_to_bQo(bQo,bg)
%Jacobian_otwisto_dot_to_bQo
%    Jacobian_otwisto_dot_to_bQo = Jacobian_otwisto_dot_to_bQo(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Mar-2025 16:01:45

bQo1 = bQo(1,:);
bQo2 = bQo(2,:);
bQo3 = bQo(3,:);
bQo4 = bQo(4,:);
bg1 = bg(1,:);
bg2 = bg(2,:);
bg3 = bg(3,:);
t2 = bQo1.*bg1.*2.0;
t3 = bQo1.*bg2.*2.0;
t4 = bQo2.*bg1.*2.0;
t5 = bQo1.*bg3.*2.0;
t6 = bQo2.*bg2.*2.0;
t7 = bQo3.*bg1.*2.0;
t8 = bQo2.*bg3.*2.0;
t9 = bQo3.*bg2.*2.0;
t10 = bQo4.*bg1.*2.0;
t11 = bQo3.*bg3.*2.0;
t12 = bQo4.*bg2.*2.0;
t13 = bQo4.*bg3.*2.0;
Jacobian_otwisto_dot_to_bQo = reshape([-t11+t12,t8-t10,-t6+t7,0.0,0.0,0.0,t9+t13,t5+t7-bQo2.*bg2.*4.0,-t3+t10-bQo2.*bg3.*4.0,0.0,0.0,0.0,-t5+t6-bQo3.*bg1.*4.0,t4+t13,t2+t12-bQo3.*bg3.*4.0,0.0,0.0,0.0,t3+t8-bQo4.*bg1.*4.0,-t2+t11-bQo4.*bg2.*4.0,t4+t9,0.0,0.0,0.0],[6,4]);
end
