# Yaml file containing the transformations between the the aruco markers and the frames of interest
# The transformations are expressed in the frame of the aruco markers
# define the transform of the frame wrt the aruco marker
# in the file are also defined the object parameters such as mass and inertia
# the viscous friction with the air is also defined
# there are also the transformations between the object and the grippers of the robots, 
# and the relative transformations between robots ans base1 and base 


b1Tb2: #transformation between the base of robot 1 and the base of robot 2
  translation: [0.0, 0.0, 0.7] 
  quaternion: [0.0, 1.0, 0.0, 0.0] # [qx, qy, qz, qw] 
  name: "b1Tb2"

bTb1: #transformation between the base frame and the base of robot 1
  translation: [0.0, 0.0, 0.0]
  quaternion: [0.0, 0.0, 0.0, 1.0]
  name: "bTb1"

gravity_vector: [0.0, 0.0, -0.0] # gravity vector

resin_block_1: # first object
  inertia_matrix: [0.250,0.250,0.250,0.01,0.01,0.01]
  viscous_friction:  [0.1,0.1,0.1,0.01,0.01,0.01] # viscous friction with the air
  oTg1:         # transformation between the object and the gripper of robot 1 - define how the object is grasped
      translation: [0.0, 0.1, -0.0] 
      quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
  oTg2:         # transformation between the object and the gripper of robot 2 - define how the object is grasped
      translation: [0.0, -0.1, 0.0] 
      quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
  aruco_transforms:
    - aruco_id: 0
      frame_transform: 
        translation: [0.0, 0.0, -0.02] 
        quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
      name: "side1_T_object"
    - aruco_id: 1
      frame_transform: 
        translation: [0.0, 0.0, -0.07] 
        quaternion: [0.0, -0.7071068, 0.0, 0.7071068] # [qx, qy, qz, qw] 
      name: "side2_T_object"
    - aruco_id: 2
      frame_transform:
        translation: [0.0, 0.0, -0.07]
        quaternion: [0.0, 0.7071068, 0.0, 0.7071068]
      name: "side3_T_object"
    - aruco_id: 3
      frame_transform:
        translation: [0.0, 0.0, -0.02]
        quaternion: [0.0, 1.0, 0.0, 0.0]
      name: "side4_T_object"

resin_block_2: # first object
  inertia_matrix: [0.1,0.1,0.1,0.01,0.01,0.01]
  viscous_friction: [0.01,0.01,0.01,0.001,0.001,0.001] # viscous friction with the air
  oTg1:         # transformation between the object and the gripper of robot 1 - define how the object is grasped
      translation: [0.0, 0.0, 0.0] 
      quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
  oTg2:         # transformation between the object and the gripper of robot 2 - define how the object is grasped
      translation: [0.0, 0.0, 0.0] 
      quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
  aruco_transforms:
    - aruco_id: 0
      frame_transform: 
        translation: [0.0, 0.0, 0.0] 
        quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
      name: "side1_T_object"
    - aruco_id: 1
      frame_transform: 
        translation: [0.0, 0.0, 0.0] 
        quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
      name: "side2_T_object"
    - aruco_id: 2
      frame_transform:
        translation: [0.0, 0.0, 0.0]
        quaternion: [0.0, 0.0, 0.0, 1.0]
      name: "side3_T_object"
    - aruco_id: 3
      frame_transform:
        translation: [0.0, 0.0, 0.0]
        quaternion: [0.0, 0.0, 0.0, 1.0]
      name: "side4_T_object"
    - aruco_id: 4
      frame_transform:
        translation: [0.0, 0.0, 0.0]
        quaternion: [0.0, 0.0, 0.0, 1.0]
      name: "side5_T_object"
  

  




