# Yaml file containing the task istructions for the cooperative manipulation task

# initial robot configuration
q_robot1_home: [-0.0562,0.4917,0.2445,-1.0458,-0.1625,1.3532,1.7347,0.0] # iiwa 7 joints + pivoting
q_robot2_home: [1.5528,-0.1953,0.0,-0.1324,-0.0311,-0.8533,0.0201,0.0] # yaskawa 7 joints + pivoting

# end effector robots (after pivoting joint)
pivotinglink1Tee1: # transformation between the end effector of robot 1 and the end effector of robot 2
  translation: [0.0, 0.0, 0.0]
  quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw]

pivotinglink2Tee2: # transformation between the end effector and the pivoting link of robot 2
  translation: [0.0, 0.0, -0.0075]
  quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw]


# camera fkine (before pivoting joint)
prepivot1Tcamera:  
  translation: [0.0965, -0.1951, -0.0048] #[0.099, -0.2190, 0.0] 
  quaternion: [ -0.5580, 0.4249, 0.5662, 0.4331] #[-0.5534,0.4401,0.5534,0.4401] # [qx, qy, qz, qw]


prepivot2Tcamera:
  translation: [0.103,-0.2070, -0.002] 
  quaternion: [-0.5852,0.3969,0.5852,0.3969] # [qx, qy, qz, qw]


# tactile sensor fkine (before pivoting joint)
prepivot1Ttactile: 
  translation: [0.0, 0.0, 0.0]
  quaternion: [0.0, 1.0, 0.0, 0.0] # [qx, qy, qz, qw]

prepivot2Ttactile: 
  translation: [0.0, 0.0, -0.0075]
  quaternion: [0.0, 1.0, 0.0, 0.0] # [qx, qy, qz, qw]


# objects to be manipulated

objects:
  - object:
      name: "resin_block_1"
      bTo_final: # object desired final pose
        translation: [0.81, 0.1, 0.22]
        quaternion: [0.0, 0.7071, -0.7071, 0.0] #[qx, qy, qz, qw] 
      qdes_robot1: [-0.0956,0.1960,0.2452,-1.4343,-0.0941,1.2533,1.7312,0.0] # iiwa 7 joints + pivoting
      qdes_robot2: [1.5528,-0.1953,0.0,-0.1324,-0.0311,-0.8533,0.0201,0.0] # yaskawa 7 joints + pivoting
  # - object:
  #     name: "resin_block_2"
  #     bTo_final: 
  #       translation: [0.8, 0.0, 0.5] 
  #       quaternion: [0.0, -0.7, 0.7, 0.0] # [qx, qy, qz, qw] 
  #     qdes_robot1: [-1.57, 0.2, 0.0, -1.16, 0.0, 1.27, 0.0, 0.0] # iiwa 7 joints + pivoting
  #     qdes_robot2: [1.57, 0.0, 0.0, 0.26, 0.0, -1.0, 0.0, 0.0] # yaskawa 7 joints + pivoting





# camera transform wrt robot end effector PRE PIVOTING JOINT! 


  #        0   -0.9997   -0.0264    0.0990
  #        0   -0.0264    0.9997   -0.2190
  #  -1.0000         0         0         0
  #        0         0         0    1.0000 prepivotTcamera no extension iiwa

  #  -0.0006   -0.9992   -0.0388    0.1559
  #   0.0287   -0.0388    0.9988   -0.2590
  #  -0.9996   -0.0006    0.0287    0.0024
  #        0         0         0    1.0000 prepivotTcamera with extension iiwa

  #        0   -0.9290   -0.3700    0.1030
  #        0   -0.3700    0.9290   -0.2070
  #  -1.0000         0         0   -0.0020
  #        0         0         0    1.0000 prepivot2Tcamera yaskawa