# Yaml file containing the task istructions for the cooperative manipulation task

# initial robot configuration
q_robot1_home: [-0.0956,0.1960,0.2452,-1.4343,-0.0941,1.2533,1.7312,0.0] # iiwa 7 joints + pivoting
q_robot2_home: [1.5528,-0.1953,0.0,-0.1324,-0.0311,-0.8533,0.0201,0.0] # yaskawa 7 joints + pivoting

# camera transform wrt robot end effector PRE PIVOTING JOINT! 
  #  -0.0006   -0.9992   -0.0388    0.1559
  #   0.0287   -0.0388    0.9988   -0.2590
  #  -0.9996   -0.0006    0.0287    0.0024
  #        0         0         0    1.0000 prepivotTcamera iiwa

  #        0   -0.9290   -0.3700    0.1030
  #        0   -0.3700    0.9290   -0.2070
  #  -1.0000         0         0   -0.0020
  #        0         0         0    1.0000 prepivot2Tcamera yaskawa

prepivot1Tcamera: 
  translation: [0.1559, -0.2590, 0.0024] 
  quaternion:  [-0.5024, 0.4830, 0.5167, 0.4973] # [qx, qy, qz, qw]



prepivot2Tcamera:
  translation: [0.103,-0.2070, -0.002] 
  quaternion: [-0.5852,0.3969,0.5852,0.3969] # [qx, qy, qz, qw]


# objects to be manipulated

objects:
  - object:
      name: "resin_block_1"
      bTo_final: # object desired final pose
        translation: [0.8, 0.0, 0.5] 
        quaternion: [ 0.5, -0.5, 0.5, 0.5 ] #[qx, qy, qz, qw] 
      qdes_robot1: [1.57, 0.2, 0.0, -1.16, 0.0, 1.27, 0.0, 0.0] # iiwa 7 joints + pivoting
      qdes_robot2: [0.0, 0.0, 0.0, 0.26, 0.0, -1.0, 0.0, 0.0] # yaskawa 7 joints + pivoting
  - object:
      name: "resin_block_2"
      bTo_final: 
        translation: [0.8, 0.0, 0.5] 
        quaternion: [0.0, -0.7, 0.7, 0.0] # [qx, qy, qz, qw] 
      qdes_robot1: [-1.57, 0.2, 0.0, -1.16, 0.0, 1.27, 0.0, 0.0] # iiwa 7 joints + pivoting
      qdes_robot2: [1.57, 0.0, 0.0, 0.26, 0.0, -1.0, 0.0, 0.0] # yaskawa 7 joints + pivoting