# Yaml file containing the task istructions for the cooperative manipulation task

# initial robot configuration
q_robot1_home: [0.0, 0.2, 0.0, -1.16, 0.0, 1.27, 0.0, 0.0] # iiwa 7 joints + pivoting
q_robot2_home: [0.0, 0.0, 0.0, 0.26, 0.0, -1.0, 0.0, 0.0] # yaskawa 7 joints + pivoting

# camera transform wrt robot end effector PRE PIVOTING JOINT! 
prepivot1Tcamera: 
  translation: [0.1, 0.1, 0.5] 
  quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw]

prepivot2Tcamera:
  translation: [0.103,-0.20, 0.0] 
  quaternion: [0.6974,-0.1167,0.6974,-0.1167] # [qx, qy, qz, qw]

# objects to be manipulated

objects:
  - object:
      name: "resin_block_1"
      bTo_final: # object desired final pose
        translation: [0.8, 0.0, 0.5] 
        quaternion: [ 0.5, -0.5, 0.5, 0.5 ] #[qx, qy, qz, qw] 
  - object:
      name: "resin_block_2"
      bTo_final: 
        translation: [0.8, 0.0, 0.5] 
        quaternion: [0.0, -0.7, 0.7, 0.0] # [qx, qy, qz, qw] 